# Generated by Django 5.0.6 on 2024-07-04 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_proveedor_correo'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='direccion',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='direccion',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
