# Generated by Django 5.0.6 on 2024-07-04 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_order_direccion_user_direccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_status',
            field=models.CharField(default='Pending', max_length=50),
        ),
        migrations.AddField(
            model_name='order',
            name='is_delivery',
            field=models.BooleanField(default=False),
        ),
    ]
