# Generated by Django 5.0.6 on 2024-07-05 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_order_delivery_status_order_is_delivery'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='imagen_perfil',
            field=models.ImageField(blank=True, null=True, upload_to='imagenes_perfil/'),
        ),
    ]
