# Generated by Django 5.0.6 on 2024-07-11 00:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_user_imagen_perfil'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fallo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('categoria', models.CharField(blank=True, max_length=100)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='fallos/')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('estado', models.CharField(default='pendiente', max_length=100)),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fallos', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
